server:
  port: 7002
eureka:
  instance:
    #hostname: localhost
    hostname: eureka7002
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  单机版本的
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka
